#!/usr/bin/env python3
"""Fix incomplete .g.cs files generated by XamlCompiler.exe Pass 1."""
import os
import re
import sys

OBJ_DIR = r"E:\SYNC\My VS\PChabit\src\PChabit.App\obj\Release\net9.0-windows10.0.22621.0"
PROJECT_DIR = r"E:\SYNC\My VS\PChabit\src\PChabit.App"

def find_gcs_files(obj_dir):
    files = []
    for root, dirs, filenames in os.walk(obj_dir):
        for f in filenames:
            if f.endswith(".g.cs") and "GlobalUsings" not in f:
                files.append(os.path.join(root, f))
    return files

def parse_connect_method(content):
    fields = []
    pattern = r"this\.(\w+)\s*=\s*global::WinRT\.CastExtensions\.As<(global::[^>]+)>\(target\)"
    for match in re.finditer(pattern, content):
        name = match.group(1)
        ftype = match.group(2)
        fields.append((name, ftype))
    return fields

def get_xaml_uri_from_checksum(content):
    match = re.search(r'#pragma checksum "([^"]+)"', content)
    if match:
        xaml_path = match.group(1)
        rel = os.path.relpath(xaml_path, PROJECT_DIR).replace("\\", "/")
        return f"ms-appx:///{rel}"
    return None

def find_class_closing_brace(lines):
    """Find the line index of the class closing brace by tracking brace depth."""
    in_class = False
    depth = 0
    class_start = -1
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not in_class:
            if "partial class" in line or re.search(r"\bclass\s+\w+", line):
                if "{" in line:
                    in_class = True
                    depth = line.count("{") - line.count("}")
                    class_start = i
                    if depth == 0:
                        # Opening brace might be on next line
                        pass
                continue
        if in_class:
            depth += line.count("{") - line.count("}")
            if depth <= 0:
                return i
    return -1

def fix_gcs_file(gcs_path):
    with open(gcs_path, "r", encoding="utf-8-sig") as f:
        content = f.read()
    
    if "void InitializeComponent" in content:
        print(f"  SKIP (already has InitializeComponent): {os.path.basename(gcs_path)}")
        return False
    
    fields = parse_connect_method(content)
    xaml_uri = get_xaml_uri_from_checksum(content)
    if not xaml_uri:
        rel = os.path.relpath(gcs_path, OBJ_DIR).replace("\\", "/")
        if rel.endswith(".g.cs"):
            rel = rel[:-5] + ".xaml"
        xaml_uri = f"ms-appx:///{rel}"
    
    missing_code = []
    missing_code.append("")
    missing_code.append("        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Microsoft.UI.Xaml.Markup.Compiler\",\" 3.0.0.2606\")]")
    missing_code.append("        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]")
    missing_code.append("        private bool _contentLoaded;")
    missing_code.append("")
    missing_code.append("        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Microsoft.UI.Xaml.Markup.Compiler\",\" 3.0.0.2606\")]")
    missing_code.append("        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]")
    missing_code.append("        public void InitializeComponent()")
    missing_code.append("        {")
    missing_code.append("            if (_contentLoaded)")
    missing_code.append("                return;")
    missing_code.append("            _contentLoaded = true;")
    missing_code.append(f"            global::Microsoft.UI.Xaml.Application.LoadComponent(this, new global::System.Uri(\"{xaml_uri}\"), global::Microsoft.UI.Xaml.Controls.Primitives.ComponentResourceLocation.Nested);")
    missing_code.append("        }")
    
    for name, ftype in fields:
        missing_code.append("")
        missing_code.append("        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Microsoft.UI.Xaml.Markup.Compiler\",\" 3.0.0.2606\")]")
        missing_code.append("        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]")
        missing_code.append(f"        internal {ftype} {name};")
    
    lines = content.split("\n")
    
    # Find class closing brace
    insert_idx = find_class_closing_brace(lines)
    
    if insert_idx < 0:
        # Fallback: find last "    }" before final "}"
        for i in range(len(lines) - 1, 0, -1):
            if lines[i].strip() == "}":
                for j in range(i - 1, -1, -1):
                    if lines[j].strip() == "}" or lines[j].rstrip().endswith("}"):
                        insert_idx = j
                        break
                break
    
    if insert_idx < 0:
        print(f"  ERROR: Could not find insertion point in {os.path.basename(gcs_path)}")
        return False
    
    new_lines = lines[:insert_idx] + missing_code + [lines[insert_idx]] + lines[insert_idx + 1:]
    new_content = "\n".join(new_lines)
    
    with open(gcs_path, "w", encoding="utf-8-sig") as f:
        f.write(new_content)
    
    print(f"  FIXED: {os.path.basename(gcs_path)} ({len(fields)} fields)")
    return True

def main():
    gcs_files = find_gcs_files(OBJ_DIR)
    print(f"Found {len(gcs_files)} .g.cs files")
    
    fixed = 0
    skipped = 0
    for f in sorted(gcs_files):
        if fix_gcs_file(f):
            fixed += 1
        else:
            skipped += 1
    
    print(f"\nDone: {fixed} fixed, {skipped} skipped")

if __name__ == "__main__":
    main()
